server:
  port: 8888

logging:
  file: mylog.log
  path: logs

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.111.14.225:3306/jiradb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: jirauser
    password: jira

mybatis:
  type-aliases-package: classpath:mapping/*Mapper.xml
  mapper-locations: classpath:mapper/*
